### ISSUE TITLE
Any documentation on how to use this sdk?

### ISSUE THREAD

**Issue by inzamam-iqbal** [checkmobi/checkmobi_android#1]
Don't you have any documentation on how to use this sdk?

**Comment by mijaelx64** [comment]
There isn't documentation here. 
Also, It should be as library so we could install directly from Gradle.

**Comment by checkmobi** [comment]
Hello, we are happy to release the Remote Config SDK https://github.com/checkmobi/remote-config-sdk-android which is the new way to integrate CheckMobi on Android.
